app/models.py
from werkzeug.security import generate_password_hash, check_password_hash
from flask_login import UserMixin
from datetime import datetime
from app import db, login
from secrets import token_urlsafe

@login.user_loader # this is built in to our instance of our login manager instanced in our overall init
def load_user(user_id): # now we're going to get our user by our passed in ID, looking it up in table
    return User.query.get(user_id)

class User(UserMixin, db.Model):
    user_id = db.Column(db.Integer, primary_key=True)
    username = db.Column(db.String, unique=True)
    email = db.Column(db.String, unique=True)
    password = db.Column(db.String)
    token = db.Column(db.String(250), unique=True)
    posts = db.relationship('Post', backref='author', lazy=True)

    def __repr__(self):
        return f'User {self.username}'
    
    def commit(self):
        db.session.add(self)
        db.session.commit()

    def hash_password(self, password):
        return generate_password_hash(password)
    
    def check_password(self, password_input):
        return check_password_hash(self.password, password_input)
    
    def add_token(self):
        setattr(self,'token', token_urlsafe(32) )
    
    def get_id(self):
        return str(self.user_id)
    
class Post(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    body = db.Column(db.String(250))
    timestamp = db.Column(db.DateTime, default=datetime.utcnow)
    user_id = db.Column(db.Integer, db.ForeignKey('user.user_id'), nullable=False)

    def __repr__(self):
        return f'Post {self.body}'
    
    def commit(self):
        db.session.add(self)
        db.session.commit()

app/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, PasswordField, SubmitField
from wtforms.validators import DataRequired, Email

class RegisterForm(FlaskForm):
    username = StringField('username', validators=[DataRequired()])
    email = StringField('email', validators=[DataRequired(), Email()])
    password = PasswordField('password', validators=[DataRequired()])
    submit = SubmitField('Register')

class SigninForm(FlaskForm):
    username = StringField('username', validators=[DataRequired()])
    password = PasswordField('password', validators=[DataRequired()])
    submit = SubmitField('Sign In')

class PostForm(FlaskForm):
	body = StringField('body', validators=[DataRequired()])
	submit = SubmitField('Publish')
        
class UserSearchForm(FlaskForm):
	user = StringField('user', validators=[DataRequired()])
	submit = SubmitField('Search')

app/__init__.py
from flask import Flask
from config import Config
from flask_sqlalchemy import SQLAlchemy
from flask_migrate import Migrate
from flask_login import LoginManager

app = Flask(__name__)
app.config.from_object(Config)
db = SQLAlchemy(app)
migrate = Migrate(app, db)
login = LoginManager(app)

login.login_view = 'auth.signin'
login.login_message = 'Please log in'
login.login_message_category = 'warning'

from app.blueprints.auth import bp as auth_bp
app.register_blueprint(auth_bp)
from app.blueprints.main import bp as main_bp
app.register_blueprint(main_bp)
from app.blueprints.social import bp as social_bp
app.register_blueprint(social_bp)
from app.blueprints.api import bp as api_bp
app.register_blueprint(api_bp)

from app import models

app/blueprints/api/__init__.py
from flask import Blueprint

bp = Blueprint('api', __name__, url_prefix='/api')

from app.blueprints.api import routes, auth_routes

app/blueprints/api/routes.py
from flask import request, jsonify
from . import bp
from app.models import Post, User
from app.blueprints.api.helpers import token_required

# we started writing some structure for what we want the API to allow
# a user to do

# receive all posts
@bp.get('/posts')
@token_required
def api_posts(thisUser):
    result = []
    # add to this list all posts in database
    thesePosts = Post.query.all() # .all() is returning all posts, where is post is a class
    for eachPost in thesePosts:
        result.append({'id': eachPost.id,
                       'body':eachPost.body,
                       'timestamp': eachPost.timestamp,
                       'author': eachPost.user_id})
        
    return jsonify(result), 200 # this 200 is returning a "success" status

# receive posts from single user
@bp.get('/posts/<username>')
@token_required
def user_posts(thisUser, username):
    thisUser = User.query.filter_by(username=username).first()
    if thisUser: # if they give us a username we query for it, if there's no match then the username give was invalid
        return jsonify([{'id': eachPost.id,
                        'body':eachPost.body,
                        'timestamp': eachPost.timestamp,
                        'author': eachPost.user_id
                        } for eachPost in thisUser.posts]), 200
    return jsonify([{'message':'Invalid username'}]), 404

# send single post
@bp.get('/post/<postid>')
@token_required
def get_post(thisUser, postid):
    try:
        thisPost = Post.query.get(postid)
        return jsonify([{'id': thisPost.id,
                        'body':thisPost.body,
                        'timestamp': thisPost.timestamp,
                        'author': thisPost.user_id
                        }]), 200
    except:
        return jsonify([{'message': 'Invalid post id'}]), 404

# make a post
@bp.post('/newPost')
@token_required
def make_post(thisUser):
    try:
        # receive post data
        thisContent = request.json
        # make an instance of a post
        # add foreign key to user id column in post table
        thisPost = Post(body=thisContent.get('body'), user_id=thisUser.user_id)
        # commit post
        thisPost.commit()
        # return message
        return jsonify([{'message':'Post Created', 'body':thisPost.body}]), 200
    except:
        return jsonify([{'message': 'invalid form data for new post'}]), 401

app/blueprints/main/__init__.py
from flask import Blueprint

bp = Blueprint('main', __name__)

from app.blueprints.main import routes

app/blueprints/main/routes.py
from . import bp
from app import app
from app.forms import UserSearchForm
from flask import render_template, g

@app.before_request
def before_request():
    g.user_search_form = UserSearchForm() # this is creating a new global variable

@bp.route('/')
def home():
    matrix = {
        'instructors': ('Sean', 'Dylan'),
        'students': ['beth', 'karim', 'allan', 'carie', 'boros']
    }
    return render_template('index.jinja', title='Home', instructors = matrix['instructors'], students=matrix['students'], user_search_form=g.user_search_form)

@bp.route('/friends')
def friends():
    return render_template('friends.jinja', title="Friends",user_search_form=g.user_search_form)

@bp.route('/about')
def about():
    return render_template('about.jinja', title='About', user_search_form=g.user_search_form)

app/blueprints/social/__init__.py
from flask import Blueprint

bp = Blueprint('social', __name__, url_prefix='/social')

from . import routes

app/blueprints/social/routes.py
from . import bp 
from flask import render_template, flash, redirect, url_for, g
from app.models import Post, User
from app.forms import PostForm
from flask_login import current_user, login_required

@bp.route('/post', methods=['GET', 'POST'])
@login_required
def post():
    form = PostForm()
    if form.validate_on_submit():
        thisPost = Post(body=form.body.data)
        thisPost.user_id = current_user.user_id
        thisPost.commit()
        # redirecting to user page (not yet built out)
        flash('Published', 'success')
        return redirect(url_for('social.user_page', username=current_user.username))
    return render_template('post.jinja', title='New Post', form=form, user_search_form=g.user_search_form)

# the <username> is using a "slug"
@bp.route('/userpage/<username>')
@login_required
def user_page(username):
    user = User.query.filter_by(username=username).first() # this should return one row of one element
    # if we didn't use.first() we'd get a list back instead of just one element.
    return render_template('user_page.jinja', title="All Posts", user = user, user_search_form=g.user_search_form)

@bp.post('/usersearch')
@login_required
def user_search():
    if g.user_search_form.validate_on_submit:
        return redirect(url_for('social.user_page', username = g.user_search_form.user.data))
    return redirect(url_for('main.home'))

app/templates/about.jinja
{% extends 'base.jinja' %}

{% block content %}
    <h2>About page</h2>
{% endblock %}

app/templates/base.jinja
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-KK94CHFLLe+nY2dmCWGMq91rCGa5gtU4mk92HdvYe+M/SXH301p5ILy+dN9+nJOZ" crossorigin="anonymous">
    <link rel="stylesheet" href="{{ url_for('static', filename = 'style.css')}}">
    {% if title %}
        <title>{{ title }}</title>
    {% else %}
        <title>Fakebook</title>
    {% endif %}
</head>
<body class="container">

    {% include 'navbar.jinja' %}

    {% with messages = get_flashed_messages(with_categories=true) %}
        {% if messages %}
        <ul style="list-style-type:none;">
            {% for category,message in messages %}
                <li class="alert alert-{{ category }} alert-dismissible fade show" role="alert">
                {{ message }}
                <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                </li>
            {% endfor %}
        </ul>
        {% endif %}
    {% endwith %}
    {% if current_user.is_authenticated %}
        <h3>Welcome {{ current_user.username }}</h3>
        {% include './includes/user_search.jinja' %}
    {% endif %}
    
    {% block content %}{% endblock %}
    
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ENjdO4Dr2bkBIFxQpeoTz1HIcje39Wm4jDKdf19U8gI4ddQ3GYNS7NTKfAdVQSZe" crossorigin="anonymous"></script>
</body>
</html>

app/templates/friends.jinja
{% extends 'base.jinja' %}

{% block content %}

    <h4>Matrix Fakebook Friends List</h4>

{% endblock %} 

app/templates/includes/user_search.jinja
<form action="{{ url_for('social.user_search') }}", method ="post">    
    {{ user_search_form.hidden_tag() }}
    <p>
        {{ user_search_form.user.label}}<br>
        {{ user_search_form.user(size=50)}}
        {% for error in user_search_form.user.errors %} 
            <span class="err-msg">{{ error }}</span>
        {% endfor %}
    </p>
    <p>
        {{ user_search_form.submit() }}
    </p>
</form>
    

app/templates/index.jinja
{% extends 'base.jinja' %}

{% block content %}

    <h1>Matrix Fakebook Testing</h1>
    <h3>Instructors</h3>
    <p>{{instructors[0]}}</p> 
    <p>{{instructors[1]}}</p>
    <h3>Students</h3>
    {% for ele in students %}
        <p>{{ ele.title() }}</p>
    {% endfor %}

{% endblock %}

app/templates/navbar.jinja
<nav class="navbar navbar-expand-lg bg-body-tertiary mt-2">
        <div class="container-fluid">
            <a class="navbar-brand" href="{{url_for('main.home')}}">Fakebook</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav">
                <li class="nav-item">
                    <a class="nav-link" href="{{url_for('main.home')}}">Home</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{{ url_for('main.about')}}">About</a>
                </li>
                {% if not current_user.is_authenticated %}
                <li class="nav-item">
                    <a class="nav-link" href="{{ url_for('auth.register')}}">Register</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{{ url_for('auth.signin')}}">Sign In</a>
                </li>
                {% else %}
                <li class="nav-item">
                    <a class="nav-link" href="{{ url_for('main.friends')}}">Friends</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{{ url_for('social.post')}}">Post</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{{ url_for('social.user_page', username=current_user.username)}}">My Page</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{{ url_for('auth.logout')}}">Logout</a>
                </li>
                {% endif %}
            </ul>
            </div>
        </div>
    </nav>

app/templates/post.jinja
{% extends 'base.jinja' %}

{% block content %}

    <h3>Publish a post</h3>
    <form action="", method ="post">    
        {{ form.hidden_tag() }}
        <p>
            {{ form.body.label}}<br>
            {{ form.body(size=50)}}
            {% for error in form.body.errors %} 
                <span class="err-msg">{{ error }}</span>
            {% endfor %}
        </p>
        <p>
            {{ form.submit() }}
        </p>
    </form>
    
{% endblock %}

app/templates/register.jinja
{% extends 'base.jinja' %}

{% block content %}
    <h4>Please register for fakebook. These fakes run...uh...not so deep.</h4>
    <form action="", method ="post">    
        {{ form.hidden_tag() }}
        <p>
            {{ form.username.label}}<br>
            {{ form.username(size=32)}}
        </p>
        <p>
            {{ form.email.label}}<br>
            {{ form.email(size=32)}}
            {% for error in form.email.errors %} 
                <span class="err-msg">{{ error }}</span>
            {% endfor %}
        </p>
        <p>
            {{ form.password.label}}<br>
            {{ form.password(size=32)}}
            {% for error in form.password.errors %} 
                <span class="err-msg">{{ error }}</span>
            {% endfor %}
        </p>
        <p>
            {{ form.submit() }}
        </p>
    </form>
{% endblock %}

app/templates/signin.jinja
{% extends 'base.jinja' %}

{% block content %}

    <h4>Can't wait to know you better...(sign in)</h4>
    <form action="", method ="post">    
        {{ form.hidden_tag() }}
        <p>
            {{ form.username.label}}<br>
            {{ form.username(size=32)}}
        </p>
        <p>
            {{ form.password.label}}<br>
            {{ form.password(size=32)}}
        </p>
        <p>
            {{ form.submit() }}
        </p>
    </form>
    
{% endblock %}

app/templates/user_page.jinja
{% extends "base.jinja" %}

{% block content %}

    <h3>{{ user.username}}'s Page</h3>

    {% for post in user.posts %}
        <p>{{ post.body }}</p>
        <p><small>{{ post.timestamp }}</small></p>
    {% endfor %}
{% endblock %}